### ISSUE TITLE
Smolder::DB::Schema::Result::TestFileTag missing

### ISSUE THREAD

**Issue by rurban** [Smolder/smolder#6]
git master:

[Dispatch] ERROR for request '/app/projects/process_add_report/1': Error executing run mode 'process_add_report': DBIx::Class::Schema::source(): Can't find source for Smolder::DB::Schema::Result::TestFileTag at /usr/local/lib/perl5/site_perl/5.14.4/Smolder/DB/Schema/Result/SmokeReport.pm line 659

**Comment by swuecho** [comment]
the problem is that the schema generated is for older version. and version update is necessary. 

so the problem is how to run a db upgrade?

**Comment by rurban** [comment]
Thanks, I can do that.
